"""Compatibility route module for conversations."""

from src.controllers.conversation_controller import (
    create_conversation,
    create_conversation_message,
    create_message_reasoning_entry,
    create_message_tool_call,
    delete_conversation,
    delete_conversation_message,
    delete_message_reasoning_entry,
    delete_message_tool_call,
    get_conversation,
    get_conversation_message,
    get_conversation_service,
    get_message_reasoning_entry,
    get_message_tool_call,
    list_conversation_messages,
    list_conversations,
    list_message_reasoning_entries,
    list_message_tool_calls,
    router,
    update_conversation,
    update_conversation_message,
    update_message_reasoning_entry,
    update_message_tool_call,
)

__all__ = [
    "create_conversation",
    "create_conversation_message",
    "create_message_reasoning_entry",
    "create_message_tool_call",
    "delete_conversation",
    "delete_conversation_message",
    "delete_message_reasoning_entry",
    "delete_message_tool_call",
    "get_conversation",
    "get_conversation_message",
    "get_conversation_service",
    "get_message_reasoning_entry",
    "get_message_tool_call",
    "list_conversation_messages",
    "list_conversations",
    "list_message_reasoning_entries",
    "list_message_tool_calls",
    "router",
    "update_conversation",
    "update_conversation_message",
    "update_message_reasoning_entry",
    "update_message_tool_call",
]
